(() => {
'use strict';
const DM=window.DM,K=DM.K;
DM.DEFAULT_TYPOGRAPHY={family:'Arial, Helvetica, sans-serif',h1Weight:'600',h1Size:'clamp(42px, 5.2vw, 74px)',h1Mobile:'clamp(38px, 12vw, 54px)',h1Line:'0.9',h1Letter:'-0.06em',h2Weight:'600',h2Size:'clamp(34px, 4.25vw, 56px)',h2Mobile:'clamp(30px, 9.5vw, 42px)',h2Line:'0.93',h2Letter:'-0.06em',leadWeight:'400',leadSize:'17px',leadLine:'1.55',bodyWeight:'400',bodySize:'16px',h3Weight:'700',h3Size:'18px',kickerWeight:'700',kickerSize:'10px',kickerLetter:'.17em'};
const parse=raw=>{const o={},r=/([a-zA-Z0-9_:-]+)="([^"]*)"/g;let m;while((m=r.exec(raw||'')))o[m[1]]=m[2];return o;};
const tag=(n,a)=>`[${n}${Object.keys(a).length?' '+Object.entries(a).map(([k,v])=>`${k}="${String(v).replace(/"/g,'&quot;')}"`).join(' '):''}]`;
const add=(a,c)=>{const x=String(a.module_class||'').split(/\s+/).filter(Boolean);if(!x.includes(c))x.push(c);a.module_class=x.join(' ');};
const txt=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const font=v=>String(v||'Arial').split(',')[0].replace(/["']/g,'').trim()||'Arial';
const safe=(v,f='')=>{const s=String(v??f).trim().replace(/[{}<>;]/g,'');return s||f;};
const hint=a=>`${a.module_class||''} ${a.admin_label||''}`.toLowerCase();
const smallLabel=h=>/kicker|eyebrow|microcopy|(?:^|\s)canal(?:\s|$)|etiqueta|label/.test(h);
DM.isDesignDisplayAttrs=(a={},content='')=>{const h=hint(a),t=txt(content),compact=!!t&&t.length<=26&&t.split(/\s+/).length<=3;if(/intro-number|editorial|oversize|oversized|giant|mega[-_ ]?word|big[-_ ]?word|display[-_ ]?word|wordmark/.test(h))return true;if(compact&&/(?:^|\s)(?:número|numero|nãºmero)(?:\s|$)/.test(h))return true;const large=Object.entries(a).some(([k,v])=>/font_size$/.test(k)&&!/_tablet$|_phone$/.test(k)&&/^\d+(?:\.\d+)?px$/.test(v)&&Number(v.slice(0,-2))>80);return compact&&large;};
const hp=l=>l===1?'header':`header_${l}`;
const belongs=(k,l)=>l===1?/^header_(?![2-6]_)/.test(k):new RegExp(`^header_${l}_`).test(k);
function copyHeading(a,from,to){if(from===to)return;const fp=hp(from),tp=hp(to);for(const[k,v]of Object.entries({...a}))if(belongs(k,from)){const target=tp+k.slice(fp.length);if(a[target]===undefined)a[target]=v;}}
function target(original,state){if(state.first){state.first=false;return 1;}if(original<=2){state.seenH2=true;return 2;}if(!state.seenH2){state.seenH2=true;return 2;}return 3;}
function applyAttrs(a,levels,h,content,r){const f=font(r.family);if(levels.has(1))Object.assign(a,{header_font:`${f}|${r.h1Weight}|||||||`,header_font_size:r.h1Size,header_font_size_phone:r.h1Mobile,header_font_size_last_edited:'on|phone',header_line_height:`${r.h1Line}em`,header_letter_spacing:r.h1Letter});if(levels.has(2))Object.assign(a,{header_2_font:`${f}|${r.h2Weight}|||||||`,header_2_font_size:r.h2Size,header_2_font_size_phone:r.h2Mobile,header_2_font_size_last_edited:'on|phone',header_2_line_height:`${r.h2Line}em`,header_2_letter_spacing:r.h2Letter});if(levels.has(3))Object.assign(a,{header_3_font:`${f}|${r.h3Weight}|||||||`,header_3_font_size:r.h3Size});if(!levels.size&&smallLabel(h))Object.assign(a,{text_font:`${f}|${r.kickerWeight}|||||||`,text_font_size:r.kickerSize,text_letter_spacing:r.kickerLetter});else if(/hero[-_ ]?lead|\blead\b/.test(h))Object.assign(a,{text_font:`${f}|${r.leadWeight}|||||||`,text_font_size:r.leadSize,text_line_height:`${r.leadLine}em`});else if(/<p\b|<li\b/i.test(content))Object.assign(a,{text_font:`${f}|${r.bodyWeight}|||||||`,text_font_size:r.bodySize});}
function normalize(input,stats,enabled,rules){const state={first:true,seenH2:false},r={...DM.DEFAULT_TYPOGRAPHY,...(rules||{})};return String(input||'').replace(/\[et_pb_text([^\]]*)\]([\s\S]*?)\[\/et_pb_text\]/gi,(full,raw,original)=>{const a=parse(raw),levels=new Set(),design=DM.isDesignDisplayAttrs(a,original);const content=original.replace(/<h([1-6])(\b[^>]*)>([\s\S]*?)<\/h\1>/gi,(m,l,extra,body)=>{const from=Number(l),to=target(from,state);levels.add(to);if(from!==to){copyHeading(a,from,to);stats.headings++;}return `<h${to}${extra}>${body}</h${to}>`;});if(enabled){const h=hint(a);if(design){add(a,'dm-design-display');stats.designProtected=(stats.designProtected||0)+1;}else{if(levels.has(1))add(a,'dm-typo-h1');if(levels.has(2))add(a,'dm-typo-h2');if(levels.has(3))add(a,'dm-typo-h3');if(!levels.size&&smallLabel(h))add(a,'dm-typo-kicker');else if(/hero[-_ ]?lead|\blead\b/.test(h))add(a,'dm-typo-lead');else if(/<p\b|<li\b/i.test(content))add(a,'dm-typo-body');applyAttrs(a,levels,h,content,r);}}return `${tag('et_pb_text',a)}${content}[/et_pb_text]`;});}
const force=(c,ch='')=>{const b=`:is(#dm-typo-force-a,.${c}):is(#dm-typo-force-b,.${c})`;return ch?`${b} ${ch}`:b;};
function cssFor(input){const r={...DM.DEFAULT_TYPOGRAPHY,...input},family=safe(r.family,DM.DEFAULT_TYPOGRAPHY.family);return `${force('dm-typo-h1','h1')}{font-family:${family}!important;font-weight:${safe(r.h1Weight,'600')}!important;font-size:${safe(r.h1Size,DM.DEFAULT_TYPOGRAPHY.h1Size)}!important;line-height:${safe(r.h1Line,'.9')}!important;letter-spacing:${safe(r.h1Letter,'-.06em')}!important;text-transform:uppercase!important}\n${force('dm-typo-h2','h2')}{font-family:${family}!important;font-weight:${safe(r.h2Weight,'600')}!important;font-size:${safe(r.h2Size,DM.DEFAULT_TYPOGRAPHY.h2Size)}!important;line-height:${safe(r.h2Line,'.93')}!important;letter-spacing:${safe(r.h2Letter,'-.06em')}!important;text-transform:uppercase!important}\n${force('dm-typo-h3','h3')}{font-family:${family}!important;font-weight:${safe(r.h3Weight,'700')}!important;font-size:${safe(r.h3Size,'18px')}!important}\n${force('dm-typo-lead')},${force('dm-typo-lead','p')}{font-family:${family}!important;font-weight:400!important;font-size:17px!important;line-height:1.55!important}\n${force('dm-typo-body')},${force('dm-typo-body','p')},${force('dm-typo-body','li')}{font-family:${family}!important;font-weight:400!important;font-size:16px!important}\n${force('dm-typo-kicker')},${force('dm-typo-kicker','*')}{font-family:${family}!important;font-weight:700!important;font-size:10px!important;letter-spacing:.17em!important;text-transform:uppercase!important}\n.dm-design-display h1,.dm-design-display h2,.dm-design-display h3{white-space:nowrap!important;word-break:normal!important;overflow-wrap:normal!important;max-width:100%!important}\n@media(max-width:767px){${force('dm-typo-h1','h1')}{font-size:${safe(r.h1Mobile,DM.DEFAULT_TYPOGRAPHY.h1Mobile)}!important}${force('dm-typo-h2','h2')}{font-size:${safe(r.h2Mobile,DM.DEFAULT_TYPOGRAPHY.h2Mobile)}!important}}`;}
function upsert(input,css){const marker=/<style id="dm-typography-rules">[\s\S]*?<\/style>/i,style=`<style id="dm-typography-rules">${css}</style>`;if(marker.test(input))return input.replace(marker,style);const code=input.indexOf('[/et_pb_code]');if(code>=0)return input.slice(0,code)+style+input.slice(code);const col=input.indexOf('[/et_pb_column]');if(col>=0)return input.slice(0,col)+DM.shortcode('et_pb_code',{admin_label:'DM · Reglas tipográficas',module_class:'dm-typography-rules',_builder_version:K.builderVersion,global_colors_info:'{}'},style)+input.slice(col);return input;}
DM.applyHeadingAndTypography=(input,options={})=>{const stats=options.stats||{headings:0,typography:0,designProtected:0};let out=normalize(input,stats,!!options.enabled,options.rules||{});if(options.enabled){out=upsert(out,cssFor(options.rules||{}));stats.typography++;}return{shortcodes:out,stats};};
})();